#  Configuration file for ActiveCraft-SBT
#  Made by CPlaiz and Silencio
# PlaceHolderAPI integrated.



#                 ---> General Settings <---
refresh-interval-ticks: 20


#                 ---> Settings for Tab <---
# Settings
# 20 Ticks = 1 Second
tab-module-enabled: true
show-ping: true

# Tab Format
tab-header:
  - '§1Tab Header Line 1'
  - '§9Tab Header Line 2'
  - '§3Tab Header Line 3'
  - '§bTab Header Line 4'

tab-footer:
  - '§bTab Footer Line 1'
  - '§3Tab Footer Line 2'
  - '§9Tab Footer Line 3'
  - '§1Tab Footer Line 4'

# Define a group's Tab prefix and suffix.
# This only works if Luckperms is installed.
# Prefixes are assigned as sorted in this list, only the highest group's prefix is applied.
# If a player has OP, the highest group's prefix in this list will be applied.
permission-groups:
  Owner:
    prefix: "§4[Owner]"
  Admin:
    prefix: "§c[Admin]"
  Mod:
    prefix: "§3[Mod]"
  Default:
    prefix: ""

# Sort groups in the tab list, descending.
# If a player has OP, the highest group in this list will be used for sorting.
group-list-sort:
  - Owner
  - Admin
  - Mod
  - Default


#                 ---> Settings for Scoreboard <---
# Settings
scoreboard-module-enabled: true

# Scoreboard Settings
title: "§bScoreboard Title"
board:
  - "Scoreboard Line 1"
  - "Scoreboard Line 2"
  - "Scoreboard Line 3"