name: ActiveCraft-SBT
version: '${project.version}'
main: de.cplaiz.activecraftsbt.ActiveCraftSBT
api-version: 1.17
authors: [ CPlaiz, Silencio ]
description: ActiveCraft-SBT
softdepend: [PlaceholderAPI]
depend: [ActiveCraft-Core]